#!/usr/bin/env python3
"""
Example Usage of Binary Classification ML Model

This script demonstrates how to use the BinaryClassifier class with both
synthetic data and custom data formats.
"""

import numpy as np
import pandas as pd
from ml_binary_classifier import BinaryClassifier, generate_sample_data


def example_with_synthetic_data():
    """
    Example using synthetic data generated by the module.
    """
    print("="*60)
    print("EXAMPLE 1: SYNTHETIC DATA")
    print("="*60)
    
    # Generate synthetic data
    X, y = generate_sample_data(n_samples=1500, n_features=15, n_informative=12)
    
    # Create classifier
    classifier = BinaryClassifier(random_state=42)
    
    # Load and process data
    classifier.load_data(X, y, test_size=0.2, val_size=0.25)
    
    # Train models (without grid search for faster execution)
    classifier.train_random_forest(use_grid_search=False)
    classifier.train_xgboost(use_grid_search=False)
    
    # Evaluate models
    classifier.evaluate_test_set()
    
    # Generate visualizations
    classifier.plot_results(save_plots=True)
    
    return classifier


def example_with_pandas_data():
    """
    Example using pandas DataFrame format.
    """
    print("\n" + "="*60)
    print("EXAMPLE 2: PANDAS DATAFRAME FORMAT")
    print("="*60)
    
    # Generate data as pandas DataFrame
    X_raw, y_raw = generate_sample_data(n_samples=1000, n_features=10, n_informative=8)
    
    # Convert to DataFrame
    feature_names = [f'feature_{i+1}' for i in range(X_raw.shape[1])]
    df = pd.DataFrame(X_raw, columns=feature_names)
    df['target'] = y_raw
    
    print(f"DataFrame shape: {df.shape}")
    print("\nDataFrame info:")
    print(df.info())
    print("\nTarget distribution:")
    print(df['target'].value_counts())
    
    # Separate features and target
    X = df.drop('target', axis=1).values
    y = df['target'].values
    
    # Create and train classifier
    classifier = BinaryClassifier(random_state=123)
    classifier.load_data(X, y, test_size=0.3, val_size=0.2)
    
    # Train models with different settings
    print("\nTraining Random Forest...")
    classifier.train_random_forest(use_grid_search=False)
    
    print("\nTraining XGBoost...")
    classifier.train_xgboost(use_grid_search=False)
    
    # Evaluate
    classifier.evaluate_test_set()
    
    return classifier


def example_with_hyperparameter_tuning():
    """
    Example demonstrating hyperparameter tuning (warning: this takes longer).
    """
    print("\n" + "="*60)
    print("EXAMPLE 3: WITH HYPERPARAMETER TUNING")
    print("="*60)
    
    # Generate smaller dataset for faster grid search
    X, y = generate_sample_data(n_samples=800, n_features=8, n_informative=6)
    
    # Create classifier
    classifier = BinaryClassifier(random_state=999)
    classifier.load_data(X, y, test_size=0.2, val_size=0.2)
    
    # Train with grid search (this will take longer)
    print("Training with hyperparameter tuning...")
    print("Note: This may take several minutes...")
    
    classifier.train_random_forest(use_grid_search=True)
    classifier.train_xgboost(use_grid_search=True)
    
    # Evaluate
    classifier.evaluate_test_set()
    
    return classifier


def demonstrate_model_usage():
    """
    Demonstrate how to use trained models for predictions.
    """
    print("\n" + "="*60)
    print("EXAMPLE 4: USING TRAINED MODELS FOR PREDICTIONS")
    print("="*60)
    
    # Generate and train on data
    X, y = generate_sample_data(n_samples=1000, n_features=10, n_informative=8)
    classifier = BinaryClassifier(random_state=42)
    classifier.load_data(X, y)
    
    # Train models
    classifier.train_random_forest(use_grid_search=False)
    classifier.train_xgboost(use_grid_search=False)
    
    # Generate new data for prediction
    X_new, _ = generate_sample_data(n_samples=10, n_features=10, n_informative=8, random_state=999)
    X_new_scaled = classifier.scaler.transform(X_new)
    
    # Make predictions with both models
    print("Making predictions on new data...")
    print(f"New data shape: {X_new.shape}")
    
    # Random Forest predictions
    rf_pred = classifier.rf_model.predict(X_new_scaled)
    rf_pred_proba = classifier.rf_model.predict_proba(X_new_scaled)
    
    # XGBoost predictions
    xgb_pred = classifier.xgb_model.predict(X_new_scaled)
    xgb_pred_proba = classifier.xgb_model.predict_proba(X_new_scaled)
    
    # Display predictions
    predictions_df = pd.DataFrame({
        'Sample': range(1, len(X_new) + 1),
        'RF_Prediction': rf_pred,
        'RF_Probability_Class_0': rf_pred_proba[:, 0],
        'RF_Probability_Class_1': rf_pred_proba[:, 1],
        'XGB_Prediction': xgb_pred,
        'XGB_Probability_Class_0': xgb_pred_proba[:, 0],
        'XGB_Probability_Class_1': xgb_pred_proba[:, 1]
    })
    
    print("\nPredictions on new data:")
    print(predictions_df.round(4))
    
    return classifier, predictions_df


def main():
    """
    Run all examples.
    """
    print("BINARY CLASSIFICATION ML MODEL - EXAMPLES")
    print("="*60)
    
    # Run examples
    try:
        # Example 1: Basic usage with synthetic data
        classifier1 = example_with_synthetic_data()
        
        # Example 2: Using pandas DataFrame
        classifier2 = example_with_pandas_data()
        
        # Example 4: Making predictions (skip grid search example for speed)
        classifier4, predictions = demonstrate_model_usage()
        
        print("\n" + "="*60)
        print("ALL EXAMPLES COMPLETED SUCCESSFULLY!")
        print("="*60)
        print("Check the generated plots and results above.")
        print("To run hyperparameter tuning example, uncomment the respective section.")
        
        return {
            'synthetic_classifier': classifier1,
            'pandas_classifier': classifier2,
            'prediction_classifier': classifier4,
            'sample_predictions': predictions
        }
        
    except Exception as e:
        print(f"Error running examples: {e}")
        return None


if __name__ == "__main__":
    results = main()